#coding:utf-8

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
sudo apt-get update -y
sudo apt-get install pypy libffi-dev make -y
wget -O - https://bitbucket.org/pypy/pypy/downloads/pypy-2.3.1-src.tar.bz2 | tar xj
sudo chown -RH vagrant:vagrant pypy-2.3.1-src
echo 'export PATH=$PATH:$HOME/pypy-2.3.1-src/rpython/bin' > .bashrc
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision "shell", inline: $script
end
