#!/usr/bin/gosh
(define one (lambda() (length '(#t))))
(define two (lambda() (+ (one) (one))))
(define x (lambda(n) (* (two) n)))
(define y (lambda(n) (+ (* (two) n) (one))))
(display (string(integer->char(x(x(x(y(x(x(one))))))))))
(display (string(integer->char(y(x(y(x(x(y(one))))))))))
(display (string(integer->char(x(x(y(y(x(y(one))))))))))
(display (string(integer->char(x(x(y(y(x(y(one))))))))))
(display (string(integer->char(y(y(y(y(x(y(one))))))))))
(display (string(integer->char(x(x(x(x(x(one)))))))))
(display (string(integer->char(y(y(y(x(y(x(one))))))))))
(display (string(integer->char(y(y(y(y(x(y(one))))))))))
(display (string(integer->char(x(y(x(x(y(y(one))))))))))
(display (string(integer->char(x(x(y(y(x(y(one))))))))))
(display (string(integer->char(x(x(y(x(x(y(one))))))))))
(display (string(integer->char(x(y(x(one)))))))